In [4]:
import numpy as np


In [5]:
#define a matrix 
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
#calculate the mean of each column
M = np.mean(A.T, axis=1)
print(M)

[3. 4.]


In [7]:
# center columns by subtracting column means
C = A - M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [8]:
#calculate covariance matrix of centered matrix 
V = np.cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [9]:
#eigendecomposition of covariance matrix
values, vectors = np.linalg.eig(V)
print(vectors)
print(values)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]


In [10]:
#project data 
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
